vars:
  - scripts_dir: scripts

stages:
  
  preprocess_documents:
    wdir: back-end

    cmd: python scripts/preprocess_documents.py
    deps:
      - ${scripts_dir}/preprocess_documents.py
      - ingestion
      - datasets/raw
    outs:
      - datasets/processed/documents.jsonl

  chunk_documents:

    cmd: python ${scripts_dir}/chunk_documents.py
    deps:
      - ${scripts_dir}/chunk_documents.py
      - back-end/services/text_chunking_service.py
      - datasets/processed/documents.jsonl
    outs:
      - datasets/chunks/chunks.jsonl

  embed_chunks:

    cmd: python ${scripts_dir}/embed_chunks.py
    deps:
      - ${scripts_dir}/embed_chunks.py
      - back-end/services/embedding_service.py
      - datasets/chunks/chunks.jsonl
    outs:
      - artifacts/embeddings/chunk_embeddings.jsonl    