vars:
  - scripts_dir: scripts

stages:
  
  preprocess_documents:
    wdir: back-end

    cmd: python -m scripts.preprocess_documents
    deps:
      - ${scripts_dir}/preprocess_documents.py
      - ingestion
      - datasets/raw
    outs:
      - datasets/processed/documents.jsonl

  chunk_documents:
    wdir: back-end
    cmd: python -m scripts.chunk_documents
    deps:
      - ${scripts_dir}/chunk_documents.py
      - services/text_chunking_service.py
      - datasets/processed/documents.jsonl
    outs:
      - datasets/chunks/chunks.jsonl

  embed_chunks:
    wdir: back-end
    cmd: python -m scripts.embed_documents
    deps:
      - ${scripts_dir}/embed_documents.py
      - services/embedding_service.py
      - datasets/chunks/chunks.jsonl
    outs:
      - artifacts/embeddings/chunk_embeddings.jsonl    
